# Numpy python

## Numpy: Numeric computing library 

Numpy (Numerical Python) is one of the core packages for numerical computing in Python. Pandas, Matplotlib, Statmodels and many other Scientific libraries rely on NumPy. 

Numpy major contributions are: 
    . Efficient numeric computation with C primitives. 
    . Efficient collections with vectorized operations.
    . An integrated and natural Linear Algebra API. 
    . A C API for connecting Numpy with libraries in C, C++, or Portran.

In [2]:
import numpy as np 

### Creating Numpy Arrays from Python list 

In [4]:
array = np.array([1,2,3,4,5,6,7])
array

array([1, 2, 3, 4, 5, 6, 7])

In [6]:
# Up cast 
np.array([3.12,4,4.3,9])

array([3.12, 4.  , 4.3 , 9.  ])

In [7]:
np.array([1,2,3,4], dtype = "float32")

array([1., 2., 3., 4.], dtype=float32)

In [9]:
a1 = np.array([1,2,3,4])

In [10]:
type(a1)

numpy.ndarray

In [12]:
a2 = np.array([[1,2,3],
             [4,5,6]])

In [13]:
type(a2)

numpy.ndarray

In [14]:
a2.shape

(2, 3)

In [15]:
a2.ndim

2

In [16]:
a2.dtype

dtype('int32')

In [17]:
a2.size

6

## Creating Numpy Arrays from Scratch

zeros, ones, full, arange, linspace

In [18]:
np.zeros([2,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.zeros([2,4]).dtype

dtype('float64')

In [20]:
np.zeros([2,4], dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [21]:
np.ones((3,5), dtype = float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
# Create an array filled with a linear sequence 
# starting at 0, ending at 20, stepping by 2 
# (this is similar to the built-in range() function)

np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [24]:
np.ones((3,5), dtype = float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
np.full((3,5), 6.9)

array([[6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9]])

In [26]:
#Create an array of five values evenly spaced between 0 and 1 
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### random 

In [30]:
# Seed for reproducibility 
np.random.seed(0)
np.random.random((3,4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492]])

In [29]:
np.random.random((4,4))

array([[0.13850707, 0.32767372, 0.52276588, 0.90344282],
       [0.62044836, 0.79901838, 0.94504589, 0.81368   ],
       [0.18682058, 0.7820743 , 0.68072094, 0.79868213],
       [0.06319719, 0.23716135, 0.25105189, 0.30986199]])

In [34]:
np.random.rand(4,4)

array([[0.38648898, 0.90259848, 0.44994999, 0.61306346],
       [0.90234858, 0.09928035, 0.96980907, 0.65314004],
       [0.17090959, 0.35815217, 0.75068614, 0.60783067],
       [0.32504723, 0.03842543, 0.63427406, 0.95894927]])

In [31]:
np.random.normal(0,1, (3,3))

array([[ 0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826],
       [ 0.3130677 , -0.85409574, -2.55298982]])

In [33]:
np.random.randint(0,10 ,(3,4))

array([[3, 2, 7, 2],
       [0, 0, 4, 5],
       [5, 6, 8, 4]])

## Array indexing & Slicing

### One dimensional subarray

In [35]:
s1 = np.random.randint(0,20, size = 6)
s1 

array([15,  3, 12,  4,  8, 14])

In [36]:
s1[4]

8

In [37]:
s1[-1]

14

### Multi-dimensional array

In [38]:
s2 = np.random.randint(0,10, (3,4))

In [39]:
s2

array([[4, 3, 7, 5],
       [5, 0, 1, 5],
       [9, 3, 0, 5]])

In [40]:
s2[1][1]

0

In [41]:
s2[1,1]

0

In [42]:
s2[1,2] = 10

In [43]:
s2

array([[ 4,  3,  7,  5],
       [ 5,  0, 10,  5],
       [ 9,  3,  0,  5]])

### Slicing 

x[start:stop:step]

In [44]:
s1

array([15,  3, 12,  4,  8, 14])

In [45]:
s1[0:3]

array([15,  3, 12])

In [46]:
s2[1:3, 0:2]

array([[5, 0],
       [9, 3]])

### Reshaping of Arrays & Transpose

In [47]:
grid = np.arange(1,10)

In [48]:
grid.shape

(9,)

In [49]:
grid.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
s = np.array([1,2,3])
s

array([1, 2, 3])

In [51]:
s.shape

(3,)

In [52]:
s.reshape(3,1)

array([[1],
       [2],
       [3]])

In [53]:
x = np.array([[1,2],
             [3,4]])

In [54]:
x

array([[1, 2],
       [3, 4]])

In [55]:
x.T

array([[1, 3],
       [2, 4]])

### Arrray Concatenation and Spliting 

In [56]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [58]:
np.concatenate((x,y), axis = 0)

array([1, 2, 3, 4, 5, 6])

In [4]:
grid = np.array([[1,2,3], 
                [4,5,6]])
grid 

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
np.concatenate((grid, grid), axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [10]:
# Vertical stack 
# vstack 
x = np.array([1,2,3])

grid = np.array([[9,0,7],
                [6,5,4]])

In [6]:
np.concatenate((grid, grid), axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [9]:
np.vstack((x,grid))

array([[1, 2, 3],
       [9, 0, 7],
       [6, 5, 4]])

In [11]:
# Horizontal stack 
# hstack
y = np.array([[99],
             [99]])
np.hstack((y,grid))

array([[99,  9,  0,  7],
       [99,  6,  5,  4]])

### Spliting of arrays 

In [12]:
x = np.array([1,2,3,4,1,21,3,21])

In [13]:
np.split(x, [3,5])

[array([1, 2, 3]), array([4, 1]), array([21,  3, 21])]

In [14]:
x1, x2, x3 = np.split(x, [3,5])

In [15]:
x1

array([1, 2, 3])

In [16]:
x2

array([4, 1])

In [17]:
x3

array([21,  3, 21])

### Broadcasting and Vectorized operations 

Broadcasting is simply a set of rules for applying binary ufuncs (e.g : adđition, substraction, multiplication, etc) on arrays of differents sizes : 

In [18]:
a = np.arange(3)
a 

array([0, 1, 2])

In [20]:
a+5 # broadcasting 

array([5, 6, 7])

In [24]:
b = np.ones((3,3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
a.shape, b.shape

((3,), (3, 3))

In [23]:
a+b 

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [25]:
c = np.arange(3).reshape(3,1)

In [26]:
a+c

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

### Manipulating & Comparing Arrays 

##### Aggregation 

Aggregation - performing the same operation on a number of things. 

In [27]:
list_number = [1,2,3]
li = np.array(list_number)
li 

array([1, 2, 3])

In [28]:
sum(li)

6

In [29]:
np.sum(li)

6

In [30]:
# Create a massive Numpy array. 
massive_array = np.random.random(10000)

In [32]:
massive_array[:5]

array([0.98573575, 0.43047773, 0.92759547, 0.70645665, 0.49895501])

In [33]:
massive_array.shape

(10000,)

In [34]:
sum(massive_array)

5003.791684172066

In [35]:
np.sum(massive_array)

5003.791684172069

In [37]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

1.01 ms ± 167 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
14.3 µs ± 1.12 µs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [38]:
np.mean(massive_array)

0.5003791684172069

In [39]:
np.max(massive_array)

0.9999195695169236

In [40]:
np.min(massive_array)

8.790440953510004e-05

In [41]:
dog_height = [600, 470, 170, 430, 300]

In [42]:
dog_height = np.array(dog_height)

In [44]:
np.std(dog_height)

147.32277488562318

In [45]:
np.var(dog_height)

21704.0

### Sorting arrays 

In [46]:
x = np.array([2,1,3,1,2,1212,134,34])

In [47]:
np.sort(x)

array([   1,    1,    2,    2,    3,   34,  134, 1212])

In [48]:
np.argsort(x)

array([1, 3, 0, 4, 2, 7, 6, 5], dtype=int64)

In [49]:
np.random.seed(42)

In [50]:
MatA = np.random.randint(0,10, size = (4,5))

In [51]:
MatA 

array([[6, 3, 7, 4, 6],
       [9, 2, 6, 7, 4],
       [3, 7, 7, 2, 5],
       [4, 1, 7, 5, 1]])

In [52]:
np.sort(MatA, axis = 0)

array([[3, 1, 6, 2, 1],
       [4, 2, 7, 4, 4],
       [6, 3, 7, 5, 5],
       [9, 7, 7, 7, 6]])

In [53]:
np.sort(MatA, axis = 1)

array([[3, 4, 6, 6, 7],
       [2, 4, 6, 7, 9],
       [2, 3, 5, 7, 7],
       [1, 1, 4, 5, 7]])

### Linear Algebra 

In [54]:
a = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])

In [55]:
b = np.array([[6,5],
             [4,3],
             [2,1]])

In [56]:
a.dot(b)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [58]:
a @ b 

array([[20, 14],
       [56, 41],
       [92, 68]])

In [60]:
b.T @ a 

array([[36, 48, 60],
       [24, 33, 42]])

### Dot Product 

In [61]:
np.random.seed(0)

sales_mounts = np.random.randint(20, size = (5, 3))

In [62]:
sales_mounts 

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [64]:
import pandas as pd 

weekly_sales = pd.DataFrame(sales_mounts, index = ["Mon", "Tues", "Wed", "Thurs", "Fri"], 
                                           columns = ["Almond Butter", "Peanut Butter", "cashew butter"])

In [65]:
weekly_sales 

Almond Butter  Peanut Butter  cashew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [66]:
# create price array 

price = np.array([10,8,12])

In [67]:
butter_prices = pd.DataFrame(price.reshape(1,3), index = ["Price"], columns = ["Almond Butter", "Peanut Butter", "Cashew Butter"])

In [68]:
butter_prices 

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [69]:
weekly_sales 

Almond Butter  Peanut Butter  cashew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [71]:
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [88]:
transpose = butter_prices.T 

weekly_sales.dot(transpose)

ValueError: matrices are not aligned