## Chi2 test about dependency between rating and final_price

# H0: Hai biến rating và final_price độc lập với nhau 
# H0: Hai biến rating và final_price phụ thuộc lẫn nhau 

In [3]:
import pandas as pd 
import numpy as np 
from scipy.stats import chi2_contingency

In [5]:
my_data = pd.read_csv("C:/Users/ADMIN/BAOHUY/Phan_tich_du_lieu/chi2_rating_final_price.csv")

In [7]:
chi2_rating_final_price = pd.DataFrame({
    "pretty_bad": my_data["pretty_bad"].to_numpy(), 
    "normal": my_data["normal"].to_numpy(), 
    "good": my_data["good"].to_numpy(), 
    "excellent": my_data["excellent"].to_numpy(), 
}, index=['cheap', 'normal', 'expensive', 'very expensive'])

In [9]:
chi2_rating_final_price

pretty_bad  normal  good  excellent
cheap                   69      47   144         31
normal                  62      41    93         15
expensive               75      46   104         17
very expensive         107      50    77         14

In [11]:
alpha = 0.05

In [13]:
chi2, p, dof, expected = chi2_contingency(chi2_rating_final_price)

In [15]:
print("\nKết quả kiểm định Chi bình phương:")
print(f"Chi2 Statistic: {chi2:.4f}")
print(f"P-Value: {p:.4f}")
print(f"Degrees of Freedom: {dof}")
print("Expected Frequencies:")
print(expected)


Kết quả kiểm định Chi bình phương:
Chi2 Statistic: 33.9815
P-Value: 0.0001
Degrees of Freedom: 9
Expected Frequencies:
[[ 91.81754032  53.97580645 122.61895161  22.58770161]
 [ 66.57560484  39.13709677  88.90927419  16.37802419]
 [ 76.35685484  44.88709677 101.97177419  18.78427419]
 [ 78.25        46.         104.5         19.25      ]]


In [17]:
if p < alpha:
    print("\nKết luận: Bác bỏ H0 (Hai biến phụ thuộc lẫn nhau).")
else:
    print("\nKết luận: Không đủ bằng chứng bác bỏ H0 (Hai biến độc lập).")


Kết luận: Bác bỏ H0 (Hai biến phụ thuộc lẫn nhau).
