## Chi2 test about dependency between rating and initial price 

# H0: Hai biến rating và initial_price độc lập với nhau 
# H0: Hai biến rating và initial_price phụ thuộc lẫn nhau 

In [60]:
import pandas as pd 
import numpy as np 
from scipy.stats import chi2_contingency

In [61]:
my_data = pd.read_csv("C:/Users/ADMIN/BAOHUY/Phan_tich_du_lieu/chi2_rating_initial_price.csv")

In [62]:
chi2_rating_initial_price = pd.DataFrame({
    "pretty_bad": my_data["pretty_bad"].to_numpy(), 
    "normal": my_data["normal"].to_numpy(), 
    "good": my_data["good"].to_numpy(), 
    "excellent": my_data["excellent"].to_numpy(), 
}, index=['cheap', 'normal', 'expensive', 'very expensive'])

In [63]:
chi2_rating_initial_price

pretty_bad  normal  good  excellent
cheap                   73      40   132         30
normal                  51      51   104         18
expensive               90      42   101         13
very expensive          99      51    81         16

In [64]:
alpha = 0.05

In [65]:
chi2, p, dof, expected = chi2_contingency(chi2_rating_initial_price)

In [66]:
print("\nKết quả kiểm định Chi bình phương:")
print(f"Chi2 Statistic: {chi2:.4f}")
print(f"P-Value: {p:.4f}")
print(f"Degrees of Freedom: {dof}")
print("Expected Frequencies:")
print(expected)


Kết quả kiểm định Chi bình phương:
Chi2 Statistic: 35.1421
P-Value: 0.0001
Degrees of Freedom: 9
Expected Frequencies:
[[ 86.76915323  51.00806452 115.87701613  21.34576613]
 [ 70.67741935  41.5483871   94.38709677  17.38709677]
 [ 77.61895161  45.62903226 103.65725806  19.09475806]
 [ 77.93447581  45.81451613 104.07862903  19.17237903]]


In [67]:
if p < alpha:
    print("\nKết luận: Bác bỏ H0 (Hai biến phụ thuộc lẫn nhau).")
else:
    print("\nKết luận: Không đủ bằng chứng bác bỏ H0 (Hai biến độc lập).")


Kết luận: Bác bỏ H0 (Hai biến phụ thuộc lẫn nhau).
