## Chi2 test about dependency between rating and review count

# H0: Hai biến rating và reviews_count độc lập với nhau 
# H1: Hai biến rating và reviews_count phụ thuộc lẫn nhau 

In [23]:
import pandas as pd 
import numpy as np 
from scipy.stats import chi2_contingency

In [24]:
my_data = pd.read_csv("C:/Users/ADMIN/BAOHUY/Phan_tich_du_lieu/chi2_rating_review_count.csv")

In [25]:
chi2_rating_reviews_count = pd.DataFrame({
    "pretty_bad": my_data["pretty_bad"].to_numpy(), 
    "normal": my_data["normal"].to_numpy(), 
    "good": my_data["good"].to_numpy(), 
    "excellent": my_data["excellent"].to_numpy(), 
}, index=['low', 'normal', 'high', 'very high'])

In [26]:
chi2_rating_reviews_count

pretty_bad  normal  good  excellent
low                69      47   144         31
normal             62      41    93         15
high               75      46   104         17
very high           0      50    77         14

In [27]:
chi2, p, dof, expected = chi2_contingency(chi2_rating_reviews_count)

In [28]:
alpha = 0.05

In [29]:
print("\nKết quả kiểm định Chi bình phương:")
print(f"Chi2 Statistic: {chi2:.4f}")
print(f"P-Value: {p:.4f}")
print(f"Degrees of Freedom: {dof}")
print("Expected Frequencies:")
print(expected)


Kết quả kiểm định Chi bình phương:
Chi2 Statistic: 66.8044
P-Value: 0.0000
Degrees of Freedom: 9
Expected Frequencies:
[[ 67.73559322  60.50169492 137.4440678   25.31864407]
 [ 49.11412429  43.86892655  99.65875706  18.35819209]
 [ 56.3299435   50.31412429 114.30056497  21.05536723]
 [ 32.82033898  29.31525424  66.59661017  12.26779661]]


In [30]:
if p < alpha:
    print("\nKết luận: Bác bỏ H0 (Hai biến phụ thuộc lẫn nhau).")
else:
    print("\nKết luận: Không đủ bằng chứng bác bỏ H0 (Hai biến độc lập).")


Kết luận: Bác bỏ H0 (Hai biến phụ thuộc lẫn nhau).
