## Pearson test

In [2]:
import pandas as pd 
import numpy as np 
from scipy.stats import pearsonr

In [4]:
amazon_data = pd.read_excel("C:/Users/ADMIN/BAOHUY/Phan_tich_du_lieu/amazon_data2.xlsx")

In [6]:
amazon_data = amazon_data.drop(columns=['seller_name.1'])

In [8]:
amazon_data.tail(10)

title         seller_name  \
982  Magnetic for iPhone SE Case 2022/3rd/2020/2nd ...       Pin¦¦¦hen¦¦¦S   
983  Qloud Cloud Wrist Rest Keyboard – Cloud Palm R...        Cre¦¦¦-ab¦¦¦   
984  Gel Pens, 6pcs 0.5mm Fine Point Smooth Writing...        Luc¦¦¦amb¦¦¦   
985  LED Desk Lamp for Office Home, Eye-Caring Desk...       Air¦¦¦v S¦¦¦e   
986  120 LED Selfie Light for Phone with Front & Ba...  RAY¦¦¦GE ¦¦¦ect¦¦¦   
987  Pentel Arts Aquash Water Brush Assorted Tips, ...        Ama¦¦¦.co¦¦¦   
988  Rubbermaid Spa Works Vanity Wastebasket, 2.25 ...        Ama¦¦¦.co¦¦¦   
989  Brother HL-L3220CDW Wireless Compact Digital C...        Ama¦¦¦.co¦¦¦   
990  Youbetia 360-Degree Rotate Pencil Holder, Offi...        You¦¦¦ia ¦¦¦   
991  HTU?Upgraded Strongest Suction Car Phone Holde...        WBR¦¦¦tor¦¦¦   

                                           description  initial_price  \
982  PinLiSheng Designed for iPhone SE 2022/iPhone ...           5.99   
983  Our Story The Qloud - designed and made by Cre...          32.00   
984  Previous page Next page 1 Signatures 2 Medical...           6.99   
985  The video showcases the product in use.The vid...          25.00   
986  The video showcases the product in use.The vid...          26.80   
987  Aquash water brushes are self-wetting brushes ...          30.80   
988  The Rubbermaid 2.25G Spaworks Wastebasket is p...          15.00   
989  The Brother HL-L3220CDW digital color printer ...         250.00   
990  Youbetia Desk Pencil Organizer 360 Degree Rota...          14.00   
991  2024 Ultimate Bendable Car Phone Holder, Suppo...          40.00   

     final_price  reviews_count  root_bs_rank  rating  bought_past_month  \
982         5.09            725           482     4.5             2000.0   
983        30.00            612          5756     4.7              500.0   
984         5.99            393           587     4.5             6000.0   
985        25.00           2519           176     4.6            10000.0   
986        24.60            128         10252     4.8              200.0   
987        17.40           5425          3716     4.7              500.0   
988         7.97           3734           422     4.7             9000.0   
989       250.00           3719          5645     4.2             1000.0   
990        14.00            328          7572     4.8              400.0   
991        40.00             64         10471     4.4              400.0   

              root_bs_category  bs_rank country_of_origin  
982  Cell Phones & Accessories       96             China  
983            Office Products       21               NaN  
984            Office Products       25               NaN  
985   Tools & Home Improvement        1               NaN  
986  Cell Phones & Accessories       73             China  
987      Arts, Crafts & Sewing       52               NaN  
988             Home & Kitchen        1               USA  
989            Office Products       16           Vietnam  
990            Office Products       54               NaN  
991  Cell Phones & Accessories       37             China

In [15]:
rating = amazon_data["rating"].to_numpy()

In [17]:
rating 

array([4. , 4.3, 4.5, 4.5, 4.7, 4.4, 4.5, 4.7, 4.6, 4.5, 4.3, 4.3, 4.4,
       4.6, 3.9, 4.6, 4.6, 4.8, 4.7, 4.4, 4.5, 4.6, 4.6, 4.6, 4.6, 4.4,
       4.3, 4.6, 4.6, 4.5, 4.5, 4.1, 4.7, 4.6, 4.6, 4.8, 4.5, 4.7, 4.7,
       4.6, 4.6, 4.7, 4.4, 4.1, 4.6, 4.4, 4.6, 4.8, 4.2, 4.5, 4.2, 4.3,
       4.6, 4.9, 4.6, 4.7, 4.8, 4.4, 4.4, 4.5, 4.6, 4.4, 4.5, 4.3, 4.5,
       4.6, 4.5, 4.8, 4.4, 4.1, 4.3, 4.6, 4.7, 4.3, 4.7, 4.2, 4.3, 4. ,
       4.5, 4.5, 4.3, 4.6, 4.6, 4.4, 4.4, 4.6, 4.8, 4.5, 4.5, 4.3, 4.5,
       4.7, 4.4, 4. , 4.6, 4.6, 4.2, 4.7, 4.4, 4.6, 4.6, 4.6, 4.6, 4.4,
       4.6, 4.3, 4.7, 4.5, 4.5, 4.3, 4.7, 4.6, 4.4, 4.8, 4.6, 4.6, 4.4,
       4.3, 4.3, 4.3, 4.5, 4.4, 4.6, 4.5, 4.7, 4.6, 4.4, 4.7, 4.7, 4.6,
       4.8, 4.5, 4.7, 4.5, 4.6, 4.4, 4.6, 4.6, 4.8, 4.6, 4.8, 4.7, 4.5,
       4.5, 4.4, 4.2, 4.3, 4.7, 4.7, 4.4, 4.6, 4.4, 4.6, 4.6, 4.6, 4.6,
       4.7, 4.6, 4.6, 4.9, 4.5, 4.7, 4.5, 4.5, 4.4, 4.6, 4.7, 4.7, 4.6,
       4.4, 4.4, 4.6, 4.6, 4.6, 4.6, 4.8, 4.5, 4.7, 4.5, 4.6, 4.

In [30]:
alpha = 0.05

## Between rating and initial price

## H0: Hệ số tương quan giữa rating và initial price bằng 0 
## H1: Hệ số tương quan giữa rating và initial price khác 0 

In [20]:
initial_price = amazon_data["initial_price"].to_numpy()

In [22]:
initial_price 

array([160.  ,   9.99,  21.  ,  14.  ,  13.  ,  80.  ,  18.  , 150.  ,
         8.7 ,  28.  ,  18.  ,  39.  ,  30.  ,  90.  ,  70.  ,  25.4 ,
        27.5 ,  80.  ,  13.  ,  40.  ,  18.  ,  11.9 ,  25.  ,   9.99,
        40.  ,  46.  , 400.  ,   9.99,  17.  ,  13.  ,   9.85,   9.99,
        12.  ,  12.  ,  14.  ,  40.  ,   9.99,  50.  ,  20.  ,  71.  ,
       100.  ,   9.99,  60.  , 220.  ,   7.99,  50.  , 140.  ,   8.99,
        30.  ,  13.  ,  50.  , 180.  ,  21.  ,   8.99,  30.  ,  34.  ,
        65.  ,  70.  ,   9.99, 126.  ,   6.27,  15.  ,  15.  ,  40.  ,
       100.  ,   9.99,   5.99,  20.  ,  58.  , 339.  ,  30.  ,  12.  ,
        40.  , 370.  ,   9.89,   5.99,  96.  ,  30.  ,  20.  ,  26.  ,
        20.  ,  13.  ,  12.5 ,  38.  ,  20.  ,  65.  ,  45.  ,  32.9 ,
       165.  , 490.  ,  20.  ,  13.  ,  48.3 , 125.  ,  13.  ,  54.  ,
        40.  ,  27.  ,  12.1 , 348.  ,   9.99,  16.  ,  70.  ,  16.  ,
        50.  ,  40.  ,   7.99,  33.  ,  17.  ,  70.  ,  15.  ,  25.  ,
      

In [24]:
r, p_value = pearsonr(initial_price , rating )

In [26]:
print(f"Hệ số tương quan Pearson: {r}")
print(f"Giá trị p-value: {p_value}")


Hệ số tương quan Pearson: -0.24694267081951823
Giá trị p-value: 3.0116801943513063e-15


In [32]:
if p_value < 0.05:
    print("Bác bỏ H0. Có mối tương quan ý nghĩa giữa hai biến.")
else:
    print("Không bác bỏ H0. Không có mối tương quan ý nghĩa giữa hai biến.")

Bác bỏ H0. Có mối tương quan ý nghĩa giữa hai biến.


## Between rating and final price 

## H0: Hệ số tương quan giữa rating và final price bằng 0 
## H1: Hệ số tương quan giữa rating và final price khác 0 

In [39]:
final_price = amazon_data["final_price"].to_numpy()

In [41]:
final_price

array([100.  ,   8.99,  19.  ,   9.99,   9.99,  50.  ,  13.4 , 150.  ,
         8.7 ,  28.  ,  16.  ,  29.  ,  20.  ,  75.  ,  65.  ,  16.6 ,
        14.3 ,  40.  ,   9.99,  25.  ,  14.  ,   7.99,  15.  ,   8.99,
        40.  ,  46.  , 400.  ,   6.99,  14.  ,  13.  ,   6.99,   9.99,
         9.95,  12.  ,  14.  ,  28.  ,   8.99,  30.  ,  16.  ,  65.3 ,
        60.  ,   5.99,  45.  , 195.  ,   7.99,  36.  , 126.  ,   4.99,
        27.9 ,   9.99,  40.  , 130.  ,  21.  ,   8.99,  27.  ,  15.5 ,
        40.  ,  50.  ,   9.99, 115.  ,   6.27,  13.  ,  15.  ,  25.  ,
       100.  ,   9.99,   5.25,  17.  ,  20.  , 269.  ,  30.  ,   7.95,
        31.  , 340.  ,   9.89,   5.99,  47.1 ,  23.  ,  17.6 ,  26.  ,
        15.  ,  13.  ,   9.98,  27.  ,  19.  ,  65.  ,  35.  ,  22.6 ,
       165.  , 400.  ,  15.  ,   7.3 ,  28.5 , 125.  ,   9.69,  50.  ,
        40.  ,  14.7 ,   9.99, 279.  ,   6.69,   9.99,  50.  ,  15.  ,
        34.6 ,  30.  ,   5.99,  30.  ,  12.  ,  66.  ,  13.7 ,  19.  ,
      

In [43]:
r, p_value = pearsonr(final_price , rating )

In [45]:
print(f"Hệ số tương quan Pearson: {r}")
print(f"Giá trị p-value: {p_value}")


Hệ số tương quan Pearson: -0.24959928428520056
Giá trị p-value: 1.4862647595393391e-15


In [47]:
if p_value < 0.05:
    print("Bác bỏ H0. Có mối tương quan ý nghĩa giữa hai biến.")
else:
    print("Không bác bỏ H0. Không có mối tương quan ý nghĩa giữa hai biến.")

Bác bỏ H0. Có mối tương quan ý nghĩa giữa hai biến.


## Between initial price and final price 

## H0: Hệ số tương quan giữa initial price và final price bằng 0 
## H1: Hệ số tương quan giữa initial price và final price bằng 0 

In [51]:
r, p_value = pearsonr(initial_price, final_price)

In [53]:
print(f"Hệ số tương quan Pearson: {r}")
print(f"Giá trị p-value: {p_value}")

Hệ số tương quan Pearson: 0.9799813160634929
Giá trị p-value: 0.0


In [55]:
if p_value < 0.05:
    print("Bác bỏ H0. Có mối tương quan ý nghĩa giữa hai biến.")
else:
    print("Không bác bỏ H0. Không có mối tương quan ý nghĩa giữa hai biến.")

Bác bỏ H0. Có mối tương quan ý nghĩa giữa hai biến.
