## Regression

In [98]:
import pandas as pd 
import numpy as np 
from scipy.stats import linregress

In [99]:
amazon_data = pd.read_excel("C:/Users/ADMIN/BAOHUY/Phan_tich_du_lieu/amazon_data2.xlsx")

In [100]:
amazon_data = amazon_data.drop(columns=['seller_name.1'])

In [101]:
amazon_data.tail(10)

title         seller_name  \
982  Magnetic for iPhone SE Case 2022/3rd/2020/2nd ...       Pin¦¦¦hen¦¦¦S   
983  Qloud Cloud Wrist Rest Keyboard – Cloud Palm R...        Cre¦¦¦-ab¦¦¦   
984  Gel Pens, 6pcs 0.5mm Fine Point Smooth Writing...        Luc¦¦¦amb¦¦¦   
985  LED Desk Lamp for Office Home, Eye-Caring Desk...       Air¦¦¦v S¦¦¦e   
986  120 LED Selfie Light for Phone with Front & Ba...  RAY¦¦¦GE ¦¦¦ect¦¦¦   
987  Pentel Arts Aquash Water Brush Assorted Tips, ...        Ama¦¦¦.co¦¦¦   
988  Rubbermaid Spa Works Vanity Wastebasket, 2.25 ...        Ama¦¦¦.co¦¦¦   
989  Brother HL-L3220CDW Wireless Compact Digital C...        Ama¦¦¦.co¦¦¦   
990  Youbetia 360-Degree Rotate Pencil Holder, Offi...        You¦¦¦ia ¦¦¦   
991  HTU?Upgraded Strongest Suction Car Phone Holde...        WBR¦¦¦tor¦¦¦   

                                           description  initial_price  \
982  PinLiSheng Designed for iPhone SE 2022/iPhone ...           5.99   
983  Our Story The Qloud - designed and made by Cre...          32.00   
984  Previous page Next page 1 Signatures 2 Medical...           6.99   
985  The video showcases the product in use.The vid...          25.00   
986  The video showcases the product in use.The vid...          26.80   
987  Aquash water brushes are self-wetting brushes ...          30.80   
988  The Rubbermaid 2.25G Spaworks Wastebasket is p...          15.00   
989  The Brother HL-L3220CDW digital color printer ...         250.00   
990  Youbetia Desk Pencil Organizer 360 Degree Rota...          14.00   
991  2024 Ultimate Bendable Car Phone Holder, Suppo...          40.00   

     final_price  reviews_count  root_bs_rank  rating  bought_past_month  \
982         5.09            725           482     4.5             2000.0   
983        30.00            612          5756     4.7              500.0   
984         5.99            393           587     4.5             6000.0   
985        25.00           2519           176     4.6            10000.0   
986        24.60            128         10252     4.8              200.0   
987        17.40           5425          3716     4.7              500.0   
988         7.97           3734           422     4.7             9000.0   
989       250.00           3719          5645     4.2             1000.0   
990        14.00            328          7572     4.8              400.0   
991        40.00             64         10471     4.4              400.0   

              root_bs_category  bs_rank country_of_origin  
982  Cell Phones & Accessories       96             China  
983            Office Products       21               NaN  
984            Office Products       25               NaN  
985   Tools & Home Improvement        1               NaN  
986  Cell Phones & Accessories       73             China  
987      Arts, Crafts & Sewing       52               NaN  
988             Home & Kitchen        1               USA  
989            Office Products       16           Vietnam  
990            Office Products       54               NaN  
991  Cell Phones & Accessories       37             China

In [102]:
initial_price = amazon_data["initial_price"].to_numpy()

In [103]:
initial_price 

array([160.  ,   9.99,  21.  ,  14.  ,  13.  ,  80.  ,  18.  , 150.  ,
         8.7 ,  28.  ,  18.  ,  39.  ,  30.  ,  90.  ,  70.  ,  25.4 ,
        27.5 ,  80.  ,  13.  ,  40.  ,  18.  ,  11.9 ,  25.  ,   9.99,
        40.  ,  46.  , 400.  ,   9.99,  17.  ,  13.  ,   9.85,   9.99,
        12.  ,  12.  ,  14.  ,  40.  ,   9.99,  50.  ,  20.  ,  71.  ,
       100.  ,   9.99,  60.  , 220.  ,   7.99,  50.  , 140.  ,   8.99,
        30.  ,  13.  ,  50.  , 180.  ,  21.  ,   8.99,  30.  ,  34.  ,
        65.  ,  70.  ,   9.99, 126.  ,   6.27,  15.  ,  15.  ,  40.  ,
       100.  ,   9.99,   5.99,  20.  ,  58.  , 339.  ,  30.  ,  12.  ,
        40.  , 370.  ,   9.89,   5.99,  96.  ,  30.  ,  20.  ,  26.  ,
        20.  ,  13.  ,  12.5 ,  38.  ,  20.  ,  65.  ,  45.  ,  32.9 ,
       165.  , 490.  ,  20.  ,  13.  ,  48.3 , 125.  ,  13.  ,  54.  ,
        40.  ,  27.  ,  12.1 , 348.  ,   9.99,  16.  ,  70.  ,  16.  ,
        50.  ,  40.  ,   7.99,  33.  ,  17.  ,  70.  ,  15.  ,  25.  ,
      

In [104]:
final_price = amazon_data["final_price"].to_numpy()

In [105]:
final_price

array([100.  ,   8.99,  19.  ,   9.99,   9.99,  50.  ,  13.4 , 150.  ,
         8.7 ,  28.  ,  16.  ,  29.  ,  20.  ,  75.  ,  65.  ,  16.6 ,
        14.3 ,  40.  ,   9.99,  25.  ,  14.  ,   7.99,  15.  ,   8.99,
        40.  ,  46.  , 400.  ,   6.99,  14.  ,  13.  ,   6.99,   9.99,
         9.95,  12.  ,  14.  ,  28.  ,   8.99,  30.  ,  16.  ,  65.3 ,
        60.  ,   5.99,  45.  , 195.  ,   7.99,  36.  , 126.  ,   4.99,
        27.9 ,   9.99,  40.  , 130.  ,  21.  ,   8.99,  27.  ,  15.5 ,
        40.  ,  50.  ,   9.99, 115.  ,   6.27,  13.  ,  15.  ,  25.  ,
       100.  ,   9.99,   5.25,  17.  ,  20.  , 269.  ,  30.  ,   7.95,
        31.  , 340.  ,   9.89,   5.99,  47.1 ,  23.  ,  17.6 ,  26.  ,
        15.  ,  13.  ,   9.98,  27.  ,  19.  ,  65.  ,  35.  ,  22.6 ,
       165.  , 400.  ,  15.  ,   7.3 ,  28.5 , 125.  ,   9.69,  50.  ,
        40.  ,  14.7 ,   9.99, 279.  ,   6.69,   9.99,  50.  ,  15.  ,
        34.6 ,  30.  ,   5.99,  30.  ,  12.  ,  66.  ,  13.7 ,  19.  ,
      

In [106]:
review_count = amazon_data["reviews_count"].to_numpy()

In [107]:
review_count

array([  7791, 140420,   3353,  10059,  14296,   4392,   6429,    494,
        53696,  13772,    217,  22478,   5344,   4608,    244,    131,
        19892,  31258,  86784,  36846,    680,   7788,    878,   1263,
         3545,   2146,   2246,   1212, 125146,   2016,   4609,    312,
         1078,    965,  10673,  43850,  26852,   1981,   1496,   4062,
          351,  20855, 103262,   1021,    331,  68199,    212,   6443,
         3827,     70,   1509,   1333,   7965,    123,   4666,   2702,
        31258,    997,   2169,    808,   1067,   4361,  10195,   7024,
          271,    620,    148,   9023,   3305,   2413,    720,   3476,
        10534,    100, 128522,    859,   2215,    685,    250,    293,
          512,    412,    311, 269769,    939,   4405,   3107,   8967,
          231,   3223,   2107,    333,   1366,    269,  91957,   1240,
          804,   3639,    659,  58038,   2835,   2183,  13340,    121,
          854,   4259,    526,   2113,   9873,    326,   1214,  11887,
      

In [108]:
alpha = 0.05

## Regression between initial price and final price 

In [110]:
slope, intercept, r_value, p_value, std_err = linregress(initial_price, final_price)

In [111]:
print(f"Phương trình hồi quy: y = {slope:.2f} * x + {intercept:.2f}")
print(f"Hệ số tương quan r: {r_value:.2f}")
print(f"Giá trị p-value: {p_value:.3f}")

Phương trình hồi quy: y = 0.83 * x + -0.24
Hệ số tương quan r: 0.98
Giá trị p-value: 0.000


## H0: R^2 = 0 
## H1: R^2 != 0 

In [113]:
if p_value < 0.05:
    print("Bác bỏ H0. Tương quan giữa hai biến initial_price và final_price là phù hợp.")
else:
    print("Không bác bỏ H0. Tương quan giữa hai biến initial_price và final_price là không phù hợp.")

Bác bỏ H0. Tương quan giữa hai biến initial_price và final_price là phù hợp.


## Regression between final_price and reviews_count 

In [115]:
slope, intercept, r_value, p_value, std_err = linregress(final_price, review_count)

In [116]:
print(f"Phương trình hồi quy: y = {slope:.2f} * x + {intercept:.2f}")
print(f"Hệ số tương quan r: {r_value:.2f}")
print(f"Giá trị p-value: {p_value:.3f}")

Phương trình hồi quy: y = -17.02 * x + 8469.71
Hệ số tương quan r: -0.05
Giá trị p-value: 0.100


## H0: R^2 = 0 
## H1: R^2 != 0 

In [118]:
if p_value < 0.05:
    print("Bác bỏ H0. Tương quan giữa hai biến final_price và reviews_count là phù hợp.")
else:
    print("Không bác bỏ H0. Tương quan giữa hai biến final_price và reviews_count là không phù hợp.")

Không bác bỏ H0. Tương quan giữa hai biến final_price và reviews_count là không phù hợp.


## Regression between initial_price and reviews_count 

In [120]:
slope, intercept, r_value, p_value, std_err = linregress(initial_price, review_count)

In [121]:
print(f"Phương trình hồi quy: y = {slope:.2f} * x + {intercept:.2f}")
print(f"Hệ số tương quan r: {r_value:.2f}")
print(f"Giá trị p-value: {p_value:.3f}")

Phương trình hồi quy: y = -12.87 * x + 8417.27
Hệ số tương quan r: -0.05
Giá trị p-value: 0.140


## H0: R^2 = 0 
## H1: R^2 != 0 

In [123]:
if p_value < 0.05:
    print("Bác bỏ H0. Tương quan giữa hai biến initial_price và reviews_count là phù hợp.")
else:
    print("Không bác bỏ H0. Tương quan giữa hai biến initial_price và reviews_count là không phù hợp.")

Không bác bỏ H0. Tương quan giữa hai biến initial_price và reviews_count là không phù hợp.
